# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: 'nodeapp'
port: '90'

image:
  repository: lopez0912/app-node
